name: App deployment
on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps: 
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: run test
        run: npm run test
      - name: finished test
        run: echo all test passed
  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: mock deployment
        run: echo deployed successfully
